### ISSUE TITLE
Register allocation needs to be done at the control-flow level

### ISSUE THREAD

**Issue by chrisseaton** [tenderlove/fisk#3]
I think you need to do register allocation at the control-flow level, not the lexical instruction level.

For example your allocator will allocate this with just two registers, re-using `r9` for both `reg1` and `reg3`, but really `reg1` is still alive.

```
reg1 = 1
reg2 = 1
head:
  goto break if reg1 > 100
  reg1 = reg1 + reg2
  reg3 = 1            # your register allocator thinks reg1 is dead at
                      # this point, so shares a register with reg3, but
                      # it's still alive - it's going to be used in the
                      # next iteration!
  reg2 = reg3
  goto head
break:
```

```ruby
reg1 = fisk.register
fisk.mov reg1, fisk.imm32(1)
reg2 = fisk.register
fisk.mov reg2, fisk.imm32(1)
fisk.put_label(:head)
fisk.cmp reg1, fisk.imm32(100)
fisk.jg(fisk.label(:break))
fisk.add reg1, reg2
reg3 = fisk.register
fisk.mov reg3, fisk.imm32(1)
fisk.mov reg2, reg3
fisk.jmp(fisk.label(:head))
fisk.put_label(:break)
fisk.assign_registers([Fisk::Registers::R9, Fisk::Registers::R10])     # should fail!
```

**Comment by tenderlove** [comment]
😩 thanks for pointing that out.  I implemented the algorithm from [this paper](http://web.cs.ucla.edu/~palsberg/course/cs132/linearscan.pdf). I really didn't want to build a graph, but I guess I have to (or at least put a caveat in the docs).  Does linear scanning just not handle this case?

**Comment by chrisseaton** [comment]
Yes I think you really do need at least some kind of control-flow graph for whole-method register allocation.

Note that the paper you're following doesn't say how to obtain live ranges - it skips over that step and says it's up to you to work it out, so you probably didn't even realise it was a thing you had to do. They start the description of their algorithm with:

> Given live variable information (obtained, for example, via data-flow analysis [Aho et al. 1986])...

Aho is the Dragon book - so it's really just saying 'read some book somewhere and find some algorithm not our problem', which isn't very helpful! Something historical that is further confusing is that many old-fashioned texts will talk about simply 'register allocation' to mean allocating registers only *within a single basic block*. Today we'd call this 'local register allocation' as opposed to 'global register allocation' mean across basic blocks and a whole function at a time. So if you look up in text books you may find an algorithm for local register allocation and accidentally try to apply it globally.

One option is to keep doing what you're doing, but note it's a *local* register allocator, and invalidate all temporary names each time a jump occurs and make using them after that an error.

Another option is to yes build a CFG - it's not as hard as you think! Here's two examples in Ruby.

https://github.com/kddnewton/regular_expression/blob/bab4ec9c962293fdf84d2c414dc2cc687fc5d447/lib/regular_expression/cfg.rb#L9-L86

https://github.com/chrisseaton/rhizome/blob/afaa60c2ef7fc51bfc22d8f412c25f16e261ae35/lib/rhizomeruby/ir/builder.rb#L40-L204

**Comment by chrisseaton** [comment]
You could also get the user to `fisk.release_register` when they're done with it? Would still be an improvement on no register allocator.

**Comment by tenderlove** [comment]
@chrisseaton awesome, thanks!  I'll study the Rhizome code and see if I can port it to X86.
